workflows:
ios-build:
name: iOS Build
environment:
flutter: 3.22.0
scripts:
- flutter pub get
- rm -rf ios # REMOVE BAD IOS FOLDER
- flutter create --platforms=ios . # MAKE FRESH, CORRECT IOS FOLDER
- flutter build ios --release --no-codesign
artifacts:
- build/ios/ipa/*.ipa
